
## Logit Model

> [@hendry2007econometric] As for the example \@ref(exm:part) `part`, in order to describe the variation in the data, we need a joint model for all the observations. Assuming ($i$) that the pairs of observations are independent, we need to describe and parametrize the joint density of $X_{i}, Y_{i}$ denoted $f\left(x_{i}, y_{i}\right)$. The definition of conditional densities implies:
> $$ f\left(x_{i}, y_{i}\right)=f\left(y_{i} | x_{i}\right) f\left(x_{i}\right) $$
> A description of the joint distribution therefore comes about by describing ($ii$) the conditional distribution of participation given schooling, which is of primary interest; and ($iii$) the marginal distribution of the length of schooling, which is of less interest in this example.
>
> The marginal density of education is much harder to describe. It would certainly require considerable institutional knowledge about the US school system prior to 1980 to provide a good description. since our primary interest is the variation in participation, it is unappealing to undertake such a detailed study. We will, therefore, seek to avoid describing the marginal distribution of the conditioning, or explanatory, variables, and draw our inference exclusively from a model based on the conditional density.
>
> The opposite factorization, $f\left(x_{i} | y_{i}\right) f\left(y_{i}\right),$ is also possible, but of less interest, as schooling happened in the past relative to participation.

The detailed discussion of exogeneity is in section \@ref(exogeneity).
