---
editor_options:
  chunk_output_type: console
---

## Mediation

- [Why is it possible to get significant F statistic (p<.001) but non-significant regressor t-tests, CrossValidated](https://stats.stackexchange.com/questions/3549/why-is-it-possible-to-get-significant-f-statistic-p-001-but-non-significant-r)
- [What's the order of correlation, CrossValidated](https://stats.stackexchange.com/questions/21350/whats-the-order-of-correlation/21357#21357)
- [Partial Correlation Interpretation](https://stats.stackexchange.com/questions/50121/partial-correlation-interpretation?rq=1)

### Mediational Hypotheses Test. by David A. Kenny in Sept 25, 2018

http://davidakenny.net/cm/mediate.htm

If the mediation model is correctly specified, the paths can be estimated by multiple regression, sometimes called ordinary least squares or OLS.  In some cases, other methods of estimation (e.g., logistic regression, multilevel modeling, and structural equal modeling) must be used instead of multiple regression.  Regardless of which data analytic method is used, the steps necessary for testing mediation are the same.

1. __Y ~ X__ Show that the causal variable is correlated with the outcome, which establishes that there is an effect that may be mediated.
2. __M ~ X__: Show that the causal variable is correlated with the mediator, which essentially involves treating the mediator as if it were an outcome variable.
3. __Y ~ M + X__ Show that the mediator affects the outcome variable. It is not sufficient just to correlate the mediator with the outcome because the mediator and the outcome may be correlated because they are both caused by the causal variable X.  Thus, the causal variable must be controlled in establishing the effect of the mediator on the outcome.
4. To establish that M completely mediates the X-Y relationship, the effect of X on Y controlling for M (path c') should be zero (see discussion below on significance testing).   The effects in both Steps 3 and 4 are estimated in the same equation.

If all four of these steps are met, then the data are consistent with the hypothesis that variable M completely mediates the X-Y relationship, and if the first three steps are met but the Step 4 is not, then partial mediation is indicated.

### Co-linearity, confounding and causation. 1.5.7 wood2017generalized
