---
editor_options:
  chunk_output_type: console
---

## Postulated Statistical Model (PSM) {#PSM}

> Regression analysis is an iterative procedure, in which data lead to a model and a fit of the model to the data is produced. The quality of the fit is then investigated, leading either to modification of the model or the fit or to adoption of the model. -- from chapter 1 in [@montgomery2012introduction]

> Economists have to proceed as in any empirical science: postulate a class of possible distributions and associated statistical models; derive appropriate estimators and their properties, assuming that the statistical model is correct; then see how well these models describe the relevant economic data. When mis-matches appear, revise the statistical model, and restart. Thus, empirical research is a process, not a one-off event. [@hendry2007econometric]

> Although we do not know how the data were really generated, by postulating various classes of statistical models that could in principle generate appropriate data, by estimating their parameters assuming the models are correct, and then by evaluating the outcomes to check for mismatches, we can learn from our mistakes and develop improved models for the next round. [@hendry2007econometric]

### Strong Exogeneity {#exogeneity}

- [Zero conditional mean assumption (how can in not hold?), CrossValidated](https://stats.stackexchange.com/questions/210083/zero-conditional-mean-assumption-how-can-in-not-hold)

> The key question that arises from this decision is whether our inferences are affected by the lack of a description of the marginal density. There are two instances where we need such distributional assumptions. [@hendry2007econometric]   
> - First, to write down the likelihood, and hence to derive estimators and test statistics.  
> - Second, to find the distributions of the estimators and other statistics in order to conduct inference.

> It suffices to look at the conditional likelihood if the parameters of the conditional and the marginal likelihood are unrelated. In the statistical literature, the explanatory variables are then called ancillary, whereas the literature on econometric time series uses the notion strong exogeneity. [@hendry2007econometric]

> If exogeneity fails, maximising the conditional likelihood and the marginal likelihood will typically not lead to an overall maximum of the joint likelihood. This, in turn, may lead to inefficient, and sometimes to biased, estimators. [@hendry2007econometric]

> Since the distribution of explanatory variables is left unspecified, we say that a conditional model is an open model as opposed to the closed models, where the joint distributions of all the variables were formulated. [@hendry2007econometric]

> Specifically, three issues arise when analysing conditional models. [@hendry2007econometric]
> - [estimation] when does maximising the conditional likelihood give the same result as maximising a joint likelihood?
> - [inference] when do features of the joint distribution need to be specified to justify the asymptotic theory?
> - [causal interpretation] when can the resulting conditional model be taken to represent a causal relation?

#### Examples {-}

> For the example \@ref(exm:census), although there is a chronological ordering, as individuals first get an education and then proceed into the labor market, the choice of educational level could depend on expected future wages. [@hendry2007econometric]

### Cause-and-Effect Relationship

> A regression model does not imply a cause-and-effect relationship between the variables. Even though a strong empirical relationship may exist between two or more variables, this cannot be considered evidence that the regressor variables and the response are related in a cause-and-effect manner. To establish causality, the relationship between the regressors and the response must have a basis outside the sample data—for example, the relationship may be suggested by theoretical considerations. Regression analysis can aid in confirming a cause-and-effect relationship, but it cannot be the sole basis of such a claim. --from chapter 1 in [@montgomery2012introduction]

### Model Interpretation

Section 5.1 econometric model in [@hendry2007econometric] provides details.
