---
editor_options:
  chunk_output_type: console
---

## Autoregressions (AR) {#AR}

### Interpretation


### Exm \@ref(exm:Fulton)

```{r}
tsi_fulton %>% ggplot() + geom_line(aes(t, p.log))
```

When using other functions in `feasts`, the univaraite time series must be specified.

```{r, echo=T}
tsi_fulton %>% feasts::gg_tsdisplay(p.log)
```

```{r, echo=T}
tsi_fulton %>% ACF(p.log) %>% autoplot()
```

#### Models

```{r, echo=T}
mods_fulton[[1]] %>% glance() %>% tab_ti()
```

```{r, echo=T}
mods_fulton[[1]] %>% tidy() %>% tab_ti()
```

```{r}
tsi_fulton %>%
  mutate(fit = fitted(mods_fulton[[1]])$.fitted) %>%
  gather(fit, p.log, key = "key", value = "price") %>%
  ggplot() +
    geom_line(aes(t, price, color = key))
```

The model residuals can be analyzed using function `gg_tsresiduals()`.

```{r}
mods_fulton[[1]] %>% gg_tsresiduals()
```

```{r}
mods_fulton[[1]] %>% residuals() %>% {.$.resid} %>% qqPlot()
```

### Inference

#### Log Likelihood Ratio Test {-}

```{R}
test_llr_tsi(mods_fulton[[1]], mods_fulton[[2]]) %>% tab_ti()
```

### Mis-Specification Analysis (MSA)

```{r}
mods_fulton[[1]] %>% test_jb_tsi() %>% tab_ti()
```

```{r}
mods_fulton[[1]] %>%
  residuals() %>%
  features(.resid, ljung_box) %>%
  tab_ti()
```
