---
editor_options:
  chunk_output_type: console
---

# Linear Regression Analysis (LRA) {#LRA}

```{r, include=F}
options(width = 80, pillar.sigfig = 5)
knitr::opts_chunk$set(
  comment = "#>",
  echo = F,
  fig.align="center"
)
rm(list = ls())
```

Following packages and functions are used in this chapter:

```{r packages, message=F, echo=T}
## basic packages
library(knitr)
library(kableExtra)
library(tidyverse)
library(conflicted)
library(magrittr)
library(broom)
## paticular packages for this project
library(lmtest)
library(corrr)
library(tseries)
library(corrplot)
library(car)
library(perturb)
library(modelr)
source("../src/funcs.R")
source("../src/tests.R")
## Data and PSMs
source("../docs/census.R")
source("../docs/recs.R")
source("../docs/part.R")
```

### Data {-}

The dataset `delivery` is from [@montgomery2012introduction]:

```{r delivery, echo=T}
dat_delivery <- 
  readxl::read_xls("../data/delivery.xls", col_names = c("i", "time", "case",
    "dist"), skip = 1)
```

The dataset `acetylene` is from [@montgomery2012introduction]:

```{r acetylene, echo=T}
dat_acetylene <-
  readxl::read_xls("../data/acetylene.xls", col_names = c("i", "p", "t_raw",
    "h_raw", "c_raw"), skip = 1) %>%
  mutate(t = (t_raw - 1212.5) / 80.623) %>%
  mutate(h = (h_raw - 12.44) / 5.662) %>%
  mutate(c = (c_raw - 0.0403) / 0.03164) %>%
  select(i, p, t, h, c)
```

### To-Learn {-}

- [x] confidence interval
- [x] MSA
- [x] Likelihood Ratio Test
- [x] strong exogeneity 
- [x] ANOVA
- [x] Orthogonalization


```{r child = '../docs/LRA-logit.Rmd'}
```

```{r child = '../docs/LRA-multi.Rmd'}
```

```{r child = '../docs/LRA-interval.Rmd'}
```

```{r child = '../docs/LRA-factor.Rmd'}
```

```{r child = '../docs/LRA-MSA.Rmd'}
```

```{r child = '../docs/LRA-mediation.Rmd'}
```

