---
editor_options:
  chunk_output_type: console
---

# Spatial-Temporal Modeling

> The spatial arrangement of these loads can have a large impact on the feasibility of micro combined heat and power systems. Combined heat and power systems are most economical when the system can be run at constant load and if all of the excess waste heat can be used. Since office buildings are large consumers of electricity for base electric applications, a non-seasonal end use, if this building was located next to residential buildings the waste heat could be fully utilized by nearby neighbors reducing energy losses. [_howard2012spatial_]

> The spatial energy consumption model by end use developed in this paper will allow different distributed generation options and energy reduction measures to emerge from urban patterns of demand. This will assist urban planners and policy makers in identifying the most promising directions for future urban energy infrastructures and for cities to meet their local energy efficiency and greenhouse gas mitigation targets. [_howard2012spatial_]
