---
editor_options:
  chunk_output_type: console
---

# Time Series Analysis (TSA) {#TSA}

```{r, include=F}
options(width = 80, pillar.sigfig = 5)
knitr::opts_chunk$set(
  comment = "#>",
  echo = F,
  fig.align="center"
)
rm(list = ls())
```

Following packages and functions are used in this chapter:

```{r, message=F, echo=T}
## Basic packages
library(knitr)
library(kableExtra)
library(tidyverse)
library(magrittr)
library(tsibble)
library(lubridate)
## Specialized packages
library(forecast)
library(fable)
library(feasts)
library(fabletools)
library(stats)
library(gets)
library(car)
source("~/GitHub/TidySimStat/src/funcs.R")
source("~/GitHub/TidySimStat/src/tests.R")
source("~/GitHub/TidySimStat/src/tests_tsi.R")
## Data and PSMs
source("~/GitHub/TidySimStat/docs/fulton.R")
```

### Data {-}

```{example, Fulton, name='Fulton', echo=T}
As an example of a time series, we will look at a data set collected from the Fulton Fish Market in New York by Kathryn Graddy. Graddy (1995) used this data set to estimate a demand and supply system, as will be discussed in Chapter 15. The full data set consists of all trades of whiting sold from one particular wholesale dealer in the 111 trading days in the period 2 December 1991 to 8 May 1992. We will look at the aggregated daily price series constructed by Angrist et al. (2000).
```

### To-Learn {-}

- [x] Autoregressions
- [x] tests for dependence
- [x] recursive graphics
- [ ] interpretation of AR models

```{r child = '../docs/TSA-NBD.Rmd'}
```

```{r child = '../docs/TSA-time.Rmd'}
```

```{r child = '../docs/TSA-independence.Rmd'}
```

```{r child = '../docs/TSA-constancy.Rmd'}
```

