---
title: "TidySimStat"
author: "Edward J. Xu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [../bib/book.bib, ../bib/packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
github-repo: edxu96/TidySimStat
description: "Stochastic Simulation and Statistics in Tidyverse."
---

# About {-}

This is the website hosting all the theories and and practices regarding stochastic simulation and statistics. It has the following features:

- `R` with Tidyverse package families is used to plot graphs and analyze results.
- Some detailed equations are included.
- With hand-written functions in the `src` folder of [GitHub/edxu96/TidySimStat](https://github.com/edxu96/TidySimStat).

### Logic behind the Book

- All datasets and packages are defined at the beignning of the chapter.
- Usually, multiple datasets are included.

### Issues Solved

- [Option to limit the depth of numbered headings](https://github.com/rstudio/bookdown/issues/495). There is no way to set the depth of section numbering, so all small sections have to be followed by `{-}`.
- [Turning off section numbering in Bookdown output](https://community.rstudio.com/t/turning-off-section-numbering-in-bookdown-output/16272).
- [Echo=FALSE and Theorems](https://github.com/rstudio/bookdown/issues/220). Remember to add `echo=T` in `theorem`-family environments, because the default value for `echo` is false.
- Every changed chapters have to be rendered, because I have set "Knit and Merge"" (K-M).
- Remember to refresh other chapters if sections of some chapter are modified, because the tables of content should be updated.
